/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pcs.Usuario;

/**
 *
 * @author felipequintanilha
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        this.setSize(600, 390);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        data_nasc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setBounds(new java.awt.Rectangle(0, 23, 800, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Seja Bem-Vindo(a),");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 50, 180, 60);

        jLabel3.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
        jLabel3.setText("Cadastro");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 10, 190, 40);

        jLabel1.setText("E qual é sua data de nascimento?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 190, 220, 30);

        jLabel4.setText("Você é menino ou menina? ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 150, 220, 30);

        jLabel5.setText("Posso saber seu nome?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 110, 220, 30);

        nome.setFont(new java.awt.Font("Luminari", 0, 14)); // NOI18N
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(370, 110, 150, 30);

        sexo.setFont(new java.awt.Font("Luminari", 0, 14)); // NOI18N
        getContentPane().add(sexo);
        sexo.setBounds(380, 150, 140, 30);

        data_nasc.setFont(new java.awt.Font("Luminari", 0, 14)); // NOI18N
        data_nasc.setToolTipText("Formato: dd/mm/aaaa");
        getContentPane().add(data_nasc);
        data_nasc.setBounds(420, 190, 100, 30);

        jButton1.setText("Terminei!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 330, 103, 29);

        fundo.setIcon(new javax.swing.ImageIcon("/Users/felipequintanilha/Documents/pcs-unirio/contos/Imagens/cadastro3.jpg")); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 600, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Criando um novo usuario:
            if(nome.getText().length()!=0 && sexo.getText().length()!=0 && data_nasc.getText().length()!=0){ //Verifica se todos os campos foram preenchidos
                Usuario usr = new Usuario(nome.getText(), sexo.getText(), data_nasc.getText());
                System.out.println("Usuario criado!!!");
                this.dispose(); //Fecha a tela após criar novo usuário
            }
            else{ //Se algum dos campos não foi preenchido
                System.out.println("Você deve ter esquecido de preencher alguma coisa...");
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data_nasc;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField sexo;
    // End of variables declaration//GEN-END:variables
}
